//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKT.DataAccess.ServiceObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMKT : DbContext
    {
        public EntitiesMKT()
            : base("name=EntitiesMKT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gerente> Gerente { get; set; }
        public virtual DbSet<SIMS_GERENTE> SIMS_GERENTE { get; set; }
        public virtual DbSet<Diario> Diario { get; set; }
        public virtual DbSet<SIMS> SIMS { get; set; }
    }
}
