//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKT.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMS
    {
        public int ID_SIMS { get; set; }
        public Nullable<int> ID_OPERADOR { get; set; }
        public Nullable<int> ID_GERENTE { get; set; }
        public string SIM { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual Gerente Gerente1 { get; set; }
    }
}
