//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKT.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMS_GERENTE
    {
        public int ID_SIM_GERENTE { get; set; }
        public int ID_SIM { get; set; }
        public int ID_GERENTE { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual SIMS SIMS { get; set; }
    }
}
