//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKT.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIMS()
        {
            this.SIMS_GERENTE = new HashSet<SIMS_GERENTE>();
        }
    
        public int ID_SIMS { get; set; }
        public Nullable<int> ID_OPERADOR { get; set; }
        public string SIM { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIMS_GERENTE> SIMS_GERENTE { get; set; }
    }
}
