//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKT.DataAccess.ServiceObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMS_GERENTE
    {
        public int ID_SIM_GERENTE { get; set; }
        public int ID_SIM { get; set; }
        public int ID_GERENTE { get; set; }
        public Nullable<System.DateTime> FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual SIMS SIMS { get; set; }
    }
}
